package com.ziplink.utils;

/**
 * Base62 utility class.
 * 
 * Maps unique numeric identifiers (64-bit longs) generated by the Snowflake algorithm
 * into highly compact, URL-safe Base62 alphanumeric strings.
 * 
 * Character set is 0-9, a-z, A-Z (62 characters).
 */
public class Base62 {

    private static final String CHARACTERS = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
    private static final int BASE = CHARACTERS.length();

    /**
     * Encodes a positive long integer value into a Base62 string representation.
     * 
     * @param value The 64-bit long integer to encode.
     * @return The Base62 encoded string.
     */
    public static String encode(long value) {
        if (value < 0) {
            throw new IllegalArgumentException("Value must be non-negative");
        }
        if (value == 0) {
            return "0";
        }

        StringBuilder sb = new StringBuilder();
        while (value > 0) {
            int remainder = (int) (value % BASE);
            sb.insert(0, CHARACTERS.charAt(remainder));
            value = value / BASE;
        }
        return sb.toString();
    }

    /**
     * Decodes a Base62 string back into its original 64-bit long integer.
     * Useful for reverse lookup or analytical inspection of short codes.
     * 
     * @param str The Base62 string to decode.
     * @return The decoded 64-bit long value.
     */
    public static long decode(String str) {
        if (str == null || str.isEmpty()) {
            throw new IllegalArgumentException("Input string cannot be null or empty");
        }

        long result = 0;
        for (int i = 0; i < str.length(); i++) {
            char c = str.charAt(i);
            int digit = CHARACTERS.indexOf(c);
            if (digit == -1) {
                throw new IllegalArgumentException("Invalid Base62 character: " + c);
            }
            result = result * BASE + digit;
        }
        return result;
    }
}
